#!/bin/bash 

set -e

version="$1"

# passing the kernel version is required
if [ -z "${version}" ]; then
	echo >&2 "W: copy-initramfs: ${DPKG_MAINTSCRIPT_PACKAGE:-kernel package} did not pass a version number"
	exit 2
fi

# Ensure boot partition is mounted
partition_root=$(findmnt -n -o SOURCE /)
partition_pkname="$(lsblk -no pkname "${partition_root}")"
partition_char=$(if [[ ${partition_pkname: -1} == [0-9] ]]; then echo p; fi)

if [[ $(findmnt -M /boot/firmware/ -n -o SOURCE) != "/dev/${partition_pkname}${partition_char}1" ]]; then
    mkdir -p /boot/firmware/
    umount -lf /boot/firmware/ 2> /dev/null || true
    mount "/dev/${partition_pkname}${partition_char}1" /boot/firmware/
fi

cp "/boot/initrd.img-${ABI}" /boot/firmware/initrd.img
cp "/boot/vmlinuz-${ABI}" /boot/firmware/vmlinuz

sync
